//Si units
export const SI = {
  mass: "kg",
  mass_A: "kg",
  mass_B: "kg",
  m1: "kg",
  m2: "kg",
  acceleration: "m/s²",
  velocity: "m/s",
  "final Velocity": "m/s",
  u1: "m/s",
  u2: "m/s",
  v1: "m/s",
  v2: "m/s",
  force: " N ",
  torque: " N.m",
  work: "J",
  power: "watt",
  "Gravitational Force": " N or Kg.m/s²",
  distance: "m",
  displacement: "m",
  time: "sec",
  angle: "°",
  "Brewster's angle": "°",
};
