//Si units
export const SI = {
  MassDefect: " kg","mass":" Kg","Mass Defect":" amu","Mass":" Kg","Mass defect":" amu",
  atomic_mass: " amu","Reactant_Mass":" amu","Product_Mass":" amu","Mass_Atom":" amu",
  carbondating_mass: "g","Initial_Amount":" g", "Final_Amount":" g","Initial Amount":"g","Final Amount":"g","molarMass":"g.mol⁻¹",
  Mass_A: "kg",
  Mass_B: "kg",
  m1: "kg",
  m2: "kg",
  acceleration: "m/s²",α:"m/s²",a:"m/s²",t:"s",g: "m/s²",
  L: "kg m²/s",I:"kg m²","M.O.I":"kg m²",τ:"N m",W:"joule",P:"watt","K.E.":"joule",
  velocity: " m/s","final Velocity": " m/s","relative velocity": " m/s","Escape Velocity": " m/s","Drift Velocity":" m/s","speed":" m/s","Speed":" m/s","Velocity":" m/s",ω:"m/s","Wave Velocity": " m/s",
  u1: "m/s",
  u2: "m/s",
  v1: "m/s",
  v2: "m/s",
  v: "m/s","RMS Velocity":" m/s","Average Velocity":" m/s","Most Probable Velocity":" m/s",
  u: "m/s",
  vₙ:"m/s",
  w: "m/s",
  p:"kg m/s",
  r:"A°",
 "λ(in A°)":"A°",
 "d(in A°)":"A°",
  "Δt₀":"s",
  "Δt":"s",
  "ΔX":" m or m^2 or m^3",
  "X":" m or m^2 or m^3",
  force: " N or Kg.m/s²","Force":" N","Magnetic Force":" Newtons",
  σ:"N/m² (Pa) ",friction:"kg m/s²",
  "Gravitational Force": " Newton",
  area:" m²","Area":" m²","Area Expansion":" m²",
  Volume: " m³","Volume Expansion":" m³","volume": " m³",
  displacement: " m",length:"m",width:"m","Final Length":" mm","Length Expansion":" m",
  angle: "°","Θ":"°",Theta:"°","Angle": "°","theta":"°","Brewster's angle" :"°",
  distance:" m",Radius:" m",R:" m",s:" m",r1:" m",r2:" m",H:" m","Distance":" m",λ:"m",Length: " m","Relative Length": "m","Wave Length": "m","Half_Length":" m","Image_Distance": " m","Object_Distance":" m","Focal Length":" m","Focal_Length":" m","Change_Length":" m","Change_Volume":" m³",
  microstates: "N",
  "Radius of Nucleus":" m",
  energy: " Joule","relative Kinetic Energy":"Joule","Energy Released": " Joule","Energy Potential Energy":" Joule","Binding Energy":" Joule","Binding Energy per Nucleon":" joule/nucleon","Heat transfered (dQ)":" Joule","Change in energy":" Joule","The amount of heat":" Joule","Work done by the system":" Joule","Kinetic Energy":" Joules","Internal Energy":" Joules",
  entropy:" joules per kelvin","Change in Entropy (dS)":" joules per kelvin",
  φ:"ev",KEmax:"ev",E:"ev",Eₙ:"ev",
  field: "N/Kg", "Gravitational Field" : "N/kg","ElectricField" : "V/m",
  time: " s",T: " s", "Time": " s", "TimePeriod":" s","Time Period":" s","Half Life":" s","Mean Life":" s","Time_year":" Year",
  frequency:"s⁻¹",
  angular_momentum: "kg-m²/s", "Angular Momentum": "kg-m²/s",
  sma: " m", "Semi-major axis": " m", "Semi_Major_Axis": " m",
  massnumber: "",
  Q_value:"MeV","Q Value":"MeV",
  DecayConstant:"s⁻¹",
  charge:" coulomb","Charge1":" coulomb","Charge2":" coulomb","Charge":" coulomb",
  current: " A","Current":" A",
  voltage: " Volt","Voltage":" Volt","Electric Potential for (inside) the Shell":" Volt","Electric Potential for (outside) the Shell":" Volt","Electric Potential for (Inside) the sphere":" Volt","Electric Potential for (Outside) the sphere":" Volt","Electric Potential for disc":" Volt","Electric Potential for ring":" Volt","Electric Potential for point charge":" Volt",
  number: "","Number":"","Turns":"","turns":"","Divisions":" Divisions","Rotations":" Rotations","moles":"","freedom":"",
  Resistance: " ohm","inductance":" Ω","Capacitive":" Ω","Inductive":" Ω",
  Resistivity:"Ω-m",
  flux: " Weber","Flux":" Weber","Electric Flux":" Nm²/C","magnet":" Tesla","electric flux":" Vm","Magnetic Flux":" Weber","Magnetic_Flux":" weber",
  SelfInductance: "Henry","Self Inductance":"Henry",
  InducedEMF:"Volts","Induced EMF":"Volts","Motional EMF":"Volts",
  EnergyDensity:"joules per cubic meter","Energy Density Of Inductor":"joules per cubic meter",
  Surface_charge_density: "Cm⁻²",
  Current_Density:" Am⁻²",
  electricfield: "N/C","Electric Field by charged Disc":"N/C","Electric Field by charged Ring":"N/C","Electric Field by charged Shell":"N/C","Electric Field by charged Sphere":"N/C","Electric field by line charge of finite length":" N/C","Electric Field by point charge":" N/C",
  magneticfield:" Tesla","magnetic":" weber","MagneticField":" Tesla","Magnetic_Field":" Tesla","Magnetic Field by the Solenoid":" T","Magnetic Field by the Toroid":" T","Magnetic Field by the Circular Coil":" T","Magnetic Field by the Infinite Sheet":" T","Magnetic Field by the Infinite Wire":" T","Magnetic Field by the Solid Cylinder":" T",
  torque: " N.m",
  work: " Joule","heat":" Joule","heatabsorb":" Joule","heatrelease":" Joule",
  power: "watt","potential Energy": "Joule","kinetic Energy": "Joule","Power of Lens":" diopter",
  height: "m","Object_Height":" m","Image_Height":" m",
  SmallReading: " mm","Least Count":" mm","LeastCount":" mm" ,"Smallest_Reading":" mm","MSR":" mm","VSR":" mm","CSR":" mm","Least_Count":" mm","Distance_Moved":" mm","Pitch":" mm","Reading":" mm",
  Stress: " Pa","Young's Modulus":" Pa","Bulk Modulus":" Pa","Young_Modulus":" Pa","Pressure":" Pa","pressure":" Pa",
  TempChange: " K","Temperature_Change":" K","tempcold":" K","temphot":" K","temperature":" K","Temperature (T)":" Kelvin","Temperature":" k",
  ExpansionCoeff:" K⁻¹","Expansion_Coeff":" K⁻¹"
};
