//Si units
export const SI = {
  MassDefect: " kg","mass":" Kg","Mass Defect":" amu","Mass":" Kg",
  atomic_mass: " amu","Reactant_Mass":" amu","Product_Mass":" amu","Mass_Atom":" amu",
  carbondating_mass: "g","Initial_Amount":" g", "Final_Amount":" g","Initial Amount":"g","Final Amount":"g",
  Mass_A: "kg",
  Mass_B: "kg",
  m1: "kg",
  m2: "kg",
  acceleration: "m/s²",
  velocity: " m/s","final Velocity": " m/s","Escape Velocity": " m/s","Drift Velocity":" m/s","speed":" m/s","Speed":" m/s","Velocity":" m/s",
  u1: "m/s",
  u2: "m/s",
  v1: "m/s",
  v2: "m/s",
  force: " N or Kg.m/s²","Force":"N","Magnetic Force":"Newtons",
  "Gravitational Force": " Newton",
  distance:" m","Distance":" m","Length": " m","Half_Length":" m",
  area:" m²","Area":" m²",
  displacement: " m",
  angle: "°","Theta":"°","Angle": "°","theta":"°",
  microstates: "N",
  Radius:" m","Radius of Nucleus":" m",
  energy: " Joule","Energy Released": " Joule","Energy Potential Energy":" Joule","Binding Energy":" Joule","Binding Energy per Nucleon":" joule/nucleon",
  field: "N/Kg", "Gravitational Field" : "N/kg","ElectricField" : "V/m",
  time: " s", "Time": " s", "TimePeriod":" s","Time Period":" s","Half Life":" s","Mean Life":" s","Time_year":" Year",
  Frequency:"s⁻¹",
  angular_momentum: "kg-m²/s", "Angular Momentum": "kg-m²/s",
  sma: " m", "Semi-major axis": " m", "Semi_Major_Axis": " m",
  massnumber: "",
  Q_value:"MeV","Q Value":"MeV",
  DecayConstant:"s⁻¹",
  charge:" coulomb","Charge1":" coulomb","Charge2":" coulomb","Charge":" coulomb",
  current: " A","Current":" A",
  voltage: " Volt","Voltage":" Volt","Electric Potential for (inside) the Shell":" Volt","Electric Potential for (outside) the Shell":" Volt","Electric Potential for (Inside) the sphere":" Volt","Electric Potential for (Outside) the sphere":" Volt","Electric Potential for disc":" Volt","Electric Potential for ring":" Volt","Electric Potential for point charge":" Volt",
  number: "","Number":"","Turns":"","turns":"",
  Resistance: " ohm","inductance":" Ω","Capacitive":" Ω","Inductive":" Ω",
  Resistivity:"Ω-m",
  flux: " Weber","Flux":" Weber","Electric Flux":" Nm²/C","magnet":" Tesla","electric flux":" Vm","Magnetic Flux":" Weber","Magnetic_Flux":" weber",
  SelfInductance: "Henry","Self Inductance":"Henry",
  InducedEMF:"Volts","Induced EMF":"Volts","Motional EMF":"Volts",
  EnergyDensity:"joules per cubic meter","Energy Density Of Inductor":"joules per cubic meter",
  Surface_charge_density: "Cm⁻²",
  Current_Density:" Am⁻²",
  electricfield: "N/C","Electric Field by charged Disc":"N/C","Electric Field by charged Ring":"N/C","Electric Field by charged Shell":"N/C","Electric Field by charged Sphere":"N/C","Electric field by line charge of finite length":" N/C","Electric Field by point charge":" N/C",
  magneticfield:" Tesla","magnetic":" weber","MagneticField":" Tesla","Magnetic_Field":" Tesla","Magnetic Field by the Solenoid":" T","Magnetic Field by the Toroid":" T","Magnetic Field by the Circular Coil":" T","Magnetic Field by the Infinite Sheet":" T","Magnetic Field by the Infinite Wire":" T","Magnetic Field by the Solid Cylinder":" T",
};

